version: '3.4'

services:
  dockerfilesamples:
    image: dockerfilesamples
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 80:80
